apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: firelites.lite.example.com
spec:
  group: lite.example.com
  names:
    kind: FireLite
    listKind: FireLiteList
    plural: firelites
    singular: firelite
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: FireLite is the Schema for the firelites API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FireLiteSpec defines the desired state of FireLite
          properties:
            image:
              type: string
            nickname:
              type: string
            port:
              format: int32
              type: integer
            size:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              type: integer
          required:
          - image
          - nickname
          - port
          - size
          type: object
        status:
          description: FireLiteStatus defines the observed state of FireLite
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
