kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-lite
subjects:
- kind: ServiceAccount
  name: operator-lite
roleRef:
  kind: Role
  name: operator-lite
  apiGroup: rbac.authorization.k8s.io
